### ISSUE TITLE
Add calculation for heterozygosity

### ISSUE THREAD

**Issue by priyanka-surana** [sanger-tol/variantcalling#39]
### Description of feature

Implement the following command either using the nf-core module. 
```
vcftools --vcf $vcf --het --out $prefix
```
- Variant file is input, it can be `vcf`, `vcf.gz` or `bcf`

This feature requested by Kamil Jaron and Alex Twyford

**Comment by gq1** [comment]
https://github.com/sanger-tol/variantcalling/pull/62
