### ISSUE TITLE
Per site nucleotide diversity

### ISSUE THREAD

**Issue by priyanka-surana** [sanger-tol/variantcalling#60]
### Description of feature

Implement the following command either using the nf-core module.
```
vcftools --vcf $vcf --site-pi --positions $locations --out $prefix
```
- Variant file is input, it can be `vcf`, `vcf.gz` or `bcf`
- You will need to patch in `positions`, it is not defined in the module. Best to combine this with `bed_arg`.
- `positions` is optional, we will most of the time not have this option

This feature requested by Alex Twyford.

**Comment by gq1** [comment]
https://vcftools.github.io/man_latest.html
```
--positions <filename>
--exclude-positions <filename>

Include or exclude a set of sites on the basis of a list of positions in a file.
```

The position file could be used as included or excluded file. Not sure what is the best way to allow user to pass the file in.
Ideally, we should have 2 inputs `positions_to_include` and `postions_to_exlcued`.

This position file can be associated with `site_pi` flag, @priyanka-surana do you know what other flag needs this file?

How is this file related to `bed_arg`?

**Comment by gq1** [comment]
https://github.com/sanger-tol/variantcalling/pull/62
