### ISSUE TITLE
Assess Popgen48/scalepopgen

### ISSUE THREAD

**Issue by muffato** [sanger-tol/variantcalling#80]
We need to review how much of our population genomics ideas [Popgen48/scalepopgen](https://github.com/Popgen48/scalepopgen) can do to determine:

- if it could be used as is
- if it could be used with modifications
- if we'd rather extract and replicate some functionality here

Links: [poster](https://summit.nextflow.io/2023/barcelona/posters/scalepopgen/)

## Summary

1. All the different tools and analyses can be independently enabled.
2. There were a couple of things to do to the input VCF files, but then the pipeline runs fine.
3. We'd want to clarify whether it's going to be part of nf-core or not.
4. We need to decide in which pipeline (scalepopgen or a new pipeline) the ROH and population size analyses should go.

## Next developments

Based on the tests above, to use scalepopgen, we would want to:

- Add automatic splitting of VCF files by chromosome
- Handle non-numeric chromosome names when plotting TajimaD and SweepFinder results

**Comment by hangxue-wustl** [comment]
Requirement for input files. 
1. All VCF files need to be splitted by the chromosomes and indexed with tabix. 
2. Sample map has two tab-delimited columns without header line. In the first column are individual IDs and in the second are population IDs

vcf_input.csv:
chrom,vcf,vcf_idx
chr1,chrom1.vcf.gz,chrom1.vcf.gz.tbi
chr2,chrom2.vcf.gz,chrom2.vcf.gz.tbi

sample.map:
ind1  pop1
ind2  pop1
ind3  pop2
ind4  pop2

**Comment by hangxue-wustl** [comment]
Downloaded supplementary data from https://doi.org/10.1093/molbev/msad207 and followed EurasianOtter_PopGen.html to obtain vcf.gz files and rename samples, and select only autosomes and bialleleic SNPs for analyses. Ran "nextflow run scalepopgen -profile singularity -params-file /global/scratch/users/hangxue/otter/vcf_publication/jul4_parameters.yml -qs 10". See output graphs at https://docs.google.com/presentation/d/1O8vFmYImrJd6p4pvSLyzwiMsf9fTAZSTaG_FJGLz8t8/edit#slide=id.p

**Comment by hangxue-wustl** [comment]
Tested PCA, Admixture, Pairwise Fst and Treemix in scalepopgen. These can run successfully with little modifications. Scalepopgen can also do Tajimas_D but plotting the Tajimas_D results requires the type of the chromosome name being integer. 
Additional potential analysis:
1. ROH identification (eg. RzooROH)
2. Estimate population-size inference (eg. GONe)

**Comment by hangxue-wustl** [comment]
I have doubled checked the label. I think the ones I am working with is labeled correctly. Yeah, I think the difference might be due to different softwares / parameters
